name: CI checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install git lsb-release sudo vim gnupg openjdk-17-jdk verilator gcc-riscv64-unknown-elf curl make gcc g++
      - name: Install sbt
        run: |
          curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup --yes
          export PATH="$PATH:~/.local/share/coursier/bin"
      - name: Run Scalafmt
        run: sbt scalafmtCheck
      - name: Static pipeline riscv-tests
        run: make RISCV_PREFIX=riscv64-unknown-elf ARCHFLAGS="-march=rv32im -mabi=ilp32" -C tests
      - name: Dynamic pipeline riscv-tests
        run: make RISCV_PREFIX=riscv64-unknown-elf CORE=riscv.CoreDynamicExtMem ARCHFLAGS="-march=rv32im -mabi=ilp32" -C tests
